services:  
  - type: web
    name: elysiajs-hello-world
    runtime: node
    repo: https://github.com/render-examples/elysiajs-hello-world
    plan: free
    envVars:
    - key: BUN_VERSION
      value: 1.2.13
    region: virginia
    buildCommand: bun install
    startCommand: bun start
version: "1"